### ISSUE TITLE
Video Links are broken

### ISSUE THREAD

**Issue by ironoa** [w3f/disc2020-scalability-and-interoperability-workshop#5]
https://github.com/w3f-webops/infrastructure/issues/31

https://disc2020-sharding-and-interoperability-workshop.w3f.community/

video links are broken, Alistair suggest to fix them if it is quick. They can be fixed using this yt [playlist](https://www.youtube.com/watch?v=3RIkMAwwgZM&list=PLvaSNyqj9rnK4uBCQctnr_4enazLcGFo6)

**Comment by ironoa** [comment]
@carinaluise maybe you want to have a look at it

**Comment by carinaluise** [comment]
@ironoa The videos should be fixed now! The issue was the JQuery script. Shall we close?

**Comment by ironoa** [comment]
great thanks ! closing it
